language: php
php:
  - 5.4

before_script:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpunit --stderr --configuration module/VuFind/tests/phpunit.xml
  - phpcs --standard=PEAR --ignore=*/config/*,*/tests/* --extensions=php --report=checkstyle $PWD/module
